cameras:
  - id: "001"
    device: "/dev/video0"
    location: "生产车间A区"
    width: 1920
    height: 1080
    framerate: 30
    detector:
      confidence_threshold: 0.45
      nms_threshold: 0.5
      engine_path: "models/yolov8s.engine"
      worker_threads: 1
      max_queue_size: 8
    streamer:
      rtsp_url: "rtsp://localhost:8554/stream_001"  # rtsp://jetson-orin-nano:8554/stream_001
      http_url: "http://fnas:8889/jetson-stream1"
      scale: 1.0
      audio_device: "hw:0,0"
      framerate: 30

  # - id: "002"
  #   device: "/dev/video2"
  #   location: "生产车间B区"
  #   width: 1920
  #   height: 1080
  #   framerate: 30
  #   detector:
  #     confidence_threshold: 0.4
  #     nms_threshold: 0.5
  #     engine_path: "models/yolov8s.engine"
  #     worker_threads: 1
  #     max_queue_size: 8
  #   streamer:
  #     rtsp_url: "rtsp://localhost:8554/stream_002"
  #     http_url: "http://fnas:8889/jetson-stream2"
  #     scale: 0.8
  #     audio_device: "hw:0,0"
  #     framerate: 30
